name: Publish release

on:
  workflow_dispatch:
    inputs:
      tag_ref:
        description: 'Tag ref to publish release for'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag_ref }}

      - name: Merge release tag to main branch
        run: |
          git fetch origin
          git checkout main
          git merge ${{ inputs.tag_ref }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
        id: get_version
      
      - name: Upload release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          body: "**Changes:**"
          files: ./target/*-${{ steps.get_version.outputs.version }}.jar
