on:
  push:
    tags:        
      - '**'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
        id: get_version
      
      - name: Upload release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release version ${{ steps.get_version.outputs.version }}
          body: "**Changes:**"
          files: ./target/*-${{ steps.get_version.outputs.version }}.jar
