name: Stage release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Bump version by segment:'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'major'
          - 'minor'
      skipPerform:
        description: 'Skip release perform'
        required: false
        default: false
        type: boolean

jobs:
  perform-release:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Perform release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with: 
          git-release-bot-name: "github-actions[bot]"
          git-release-bot-email: "41898282+github-actions[bot]@users.noreply.github.com"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          version-major: ${{ inputs.releaseType == 'major' }}
          version-minor: ${{ inputs.releaseType == 'minor' }}
          release-branch-name: 'main'
          maven-args: "-Dmaven.javadoc.skip=true -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
